<?php

namespace AppBundle\Repository;

/**
 * PresentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresentationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des articles de presentation
     */
    public function findPresentation($slug, $limit, $offset)
    {
        return $q = $this->createQueryBuilder('p')
                         ->where('p.rubrique LIKE :slug')
                         ->andWhere('p.statut = 1')
                         ->orderBy('p.id', 'DESC')
                         ->setFirstResult($offset)
                         ->setMaxResults($limit)
                         ->setParameter('slug', '%'.$slug.'%')
                         ->getQuery()->getResult()
            ;
    }
}
