<?php

namespace AppBundle\Repository;

/**
 * TreichenjoieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreichenjoieRepository extends \Doctrine\ORM\EntityRepository
{
}
